apiVersion: v2
name: cosmoshub-rpc
description: A Helm chart for deploying a Cosmoshub node
type: application
version: 1.0.3
appVersion: v22.3.1
maintainers:
  - name: vince
    email: vince@nodeify.net
keywords:
  - cosmoshub
  - blockchain
  - rpc
annotations:
  lookupName: "ghcr.io/cosmos/gaia"
home: https://nodeify.net
sources:
  - https://github.com/cosmos/gaia
