apiVersion: v2
name: cosmoshub-rpc
description: A Helm chart for deploying a Cosmoshub node
type: application
version: 1.0.0
appVersion: v21.0.0
maintainers:
  - name: vince
    email: vince@nodeify.net
keywords:
  - cosmoshub
  - blockchain
  - rpc
home: https://nodeify.net
sources:
  - https://github.com/cosmos/gaia
