# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "indexer-tools.fullname" . }}
  labels: {{- include "indexer-tools.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "indexer-tools.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "indexer-tools.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "indexer-tools.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: install-deps
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: 
            - /bin/sh
            - -c
            - |
              cd /app && yarn add http-proxy-middleware
          volumeMounts:
            - name: node-modules
              mountPath: /app/node_modules
        - name: build
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["yarn", "build"]
          volumeMounts:
            - name: dist-volume
              mountPath: /app/dist
            - name: node-modules
              mountPath: /app/node_modules
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.env.variables }}
          env:
            {{- range .Values.env.variables }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: app-volume
              mountPath: /app/public
            - name: dist-volume
              mountPath: /app/dist
            - name: node-modules
              mountPath: /app/node_modules
            - name: server-config
              mountPath: /app/server.js
              subPath: server.js
          resources: {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe: {{- toYaml .Values.healthCheck.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.healthCheck.readinessProbe | nindent 12 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: app-volume
          emptyDir: {}
        - name: dist-volume
          emptyDir: {}
        - name: node-modules
          emptyDir: {}
        - name: server-config
          configMap:
            name: {{ include "indexer-tools.fullname" . }}-server