{{- $values := $.Values.substreams_sink_noop }}
{{- $componentName := "substreams-sink-noop" }}
{{- $componentLabel := include "substreams_sink_noop.componentLabelFor" $componentName }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "substreams_sink_noop.fullname" . }}
  labels:
    {{- include "substreams_sink_noop.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  type: {{ $values.service.type }}
  ports:
    - port: {{ index $values.service.ports "grpc" }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ index $values.service.ports "metrics" }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "substreams_sink_noop.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
